--Run this script under sys as SYSDBA

ALTER SESSION SET "_ORACLE_SCRIPT"= TRUE;

CREATE USER DIPLOMA IDENTIFIED BY DIPLOMA123;

GRANT CONNECT, RESOURCE, DBA TO DIPLOMA;
--
-- CREATE DIRECTORY BLKLKUP_DIR AS '/opt/oracle/oradata/ORCL12/PDB112/';
-- GRANT READ, WRITE ON DIRECTORY BLKLKUP_DIR TO DIPLOMA;